services:
  - type: web
    name: zaks-deo
    runtime: python
    buildCommand: apt-get install -y ffmpeg && pip install -U yt-dlp && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
